package com.share.service;

import java.math.BigDecimal;
import java.util.List;

import com.share.dto.DistrictsDTO;
import com.share.dto.FileDTO;
import com.share.dto.FunctionDTO;
import com.share.dto.MenuDTO;
import com.share.dto.OrganizationDTO;
import com.share.dto.PrivilegeDTO;
import com.share.dto.RoleDTO;
import com.share.dto.UserDTO;
import com.share.dto.UsergroupDTO;
import com.share.model.SysFprelation;
import com.share.model.SysGrrelation;
import com.share.model.SysMenus;
import com.share.model.SysMprelation;
import com.share.model.SysPfrelation;
import com.share.model.SysRprelation;
import com.share.model.SysUgrelation;
import com.share.model.SysUrrelation;
import com.share.model.SysVGr;
import com.share.model.SysVMp;
import com.share.model.SysVRp;
import com.share.model.SysVUg;
import com.share.model.SysVUr;
import com.share.util.Pager;

public interface SysService {
	public List<DistrictsDTO> querySYSDistrict(String hql, Object[] param);
	public void saveSYSDistrict(DistrictsDTO districtsDTO);
	public List<DistrictsDTO> querySYSDistrict(DistrictsDTO districtsDTO);
	public int updateSYSDistrict(String id);
	public List<OrganizationDTO> querySYSOrgs(String hql, Object[] param);
	public void saveSYSOrg(OrganizationDTO organizationDTO);
	public List<UserDTO> querySYSUsers(Pager pager,List<Object> param);
	public void saveSYSUser(UserDTO userDTO);
	public UserDTO querySYSUserById(Long userId);
	public void updateSYSUserById(Long userId);
	public List<UsergroupDTO> querySYSUserGroupAll();
	public List<UserDTO> querySYSUsers(List<Object> param);
	public void saveSYSUgrelation(List<SysUgrelation> list);
	public void saveSysUsergroup(String ugName);
	public void delSysUsergroup(String ugId);
	public List<RoleDTO> querySYSRoleAll();
	public void saveSysRole(String rolename);
	public void delSysRole(String roleId);
	public List<UserDTO> querySYSUserAll();
	public void saveSYSGrrelation(List<SysGrrelation> grrs);
	public void saveSYSUrrelation(List<SysUrrelation> urrs);
	public List<PrivilegeDTO> querySYSPrivilegeAll();
	public List<MenuDTO> querySYSMenusAll();
	public List<FunctionDTO> querySYSFunctionAll();
	public List<FileDTO> querySYSFileAll();
	public void saveSysPrivilege(PrivilegeDTO pdto);
	public void delSysPrivilege(String privilegeId);
	public void saveSYSRprelation(List<SysRprelation> rrs);
	public void saveSYSMprelation(List<SysMprelation> mrs);
	public void saveSYSPfrelation(List<SysPfrelation> prs);
	public void saveSYSFprelation(List<SysFprelation> frs);
	public List<SysVUg> querySYSUgUsers(BigDecimal ugId);
	public List<SysVGr> querySYSVGr(BigDecimal roleId);
	public List<SysVUr> querySYSVUr(BigDecimal roleId);
	public List<SysVRp> querySYSVRp(BigDecimal privilegeId);
	public List<SysVMp> querySYSVMp(BigDecimal privilegeId);
	public List<SysMenus> queryMenuCodeByPmid(String menuId);
	public List<SysMenus> queryMenuCodeById(String menuId);
	public void createMenu(MenuDTO menuDTO);
	public int delMenu(Long menuId);
}
